//
//  File.swift
//  
//
//  Created by Jia Chen Yee on 27/3/23.
//

import Foundation

public enum GatewayEvent: String {
    case ready = "READY"
    case resumed = "RESUMED"
    case channelCreate = "CHANNEL_CREATE"
    case channelUpdate = "CHANNEL_UPDATE"
    case channelDelete = "CHANNEL_DELETE"
    case channelPinsUpdate = "CHANNEL_PINS_UPDATE"
    case threadCreate = "THREAD_CREATE"
    case threadUpdate = "THREAD_UPDATE"
    case threadDelete = "THREAD_DELETE"
    case threadListSync = "THREAD_LIST_SYNC"
    case threadMemberUpdate = "THREAD_MEMBER_UPDATE"
    case threadMembersUpdate = "THREAD_MEMBERS_UPDATE"
    case guildCreate = "GUILD_CREATE"
    case guildUpdate = "GUILD_UPDATE"
    case guildDelete = "GUILD_DELETE"
    case guildBanAdd = "GUILD_BAN_ADD"
    case guildBanRemove = "GUILD_BAN_REMOVE"
    case guildEmojisUpdate = "GUILD_EMOJIS_UPDATE"
    case guildStickersUpdate = "GUILD_STICKERS_UPDATE"
    case guildIntegrationsUpdate = "GUILD_INTEGRATIONS_UPDATE"
    case guildMemberAdd = "GUILD_MEMBER_ADD"
    case guildMemberRemove = "GUILD_MEMBER_REMOVE"
    case guildMemberUpdate = "GUILD_MEMBER_UPDATE"
    case guildMembersChunk = "GUILD_MEMBERS_CHUNK"
    case guildRoleCreate = "GUILD_ROLE_CREATE"
    case guildRoleUpdate = "GUILD_ROLE_UPDATE"
    case guildRoleDelete = "GUILD_ROLE_DELETE"
    case guildScheduledEventCreate = "GUILD_SCHEDULED_EVENT_CREATE"
    case guildScheduledEventUpdate = "GUILD_SCHEDULED_EVENT_UPDATE"
    case guildScheduledEventDelete = "GUILD_SCHEDULED_EVENT_DELETE"
    case guildScheduledEventUserAdd = "GUILD_SCHEDULED_EVENT_USER_ADD"
    case guildScheduledEventUserRemove = "GUILD_SCHEDULED_EVENT_USER_REMOVE"
    case guildAuditLogEntryCreate = "GUILD_AUDIT_LOG_ENTRY_CREATE"
    case integrationCreate = "INTEGRATION_CREATE"
    case integrationUpdate = "INTEGRATION_UPDATE"
    case integrationDelete = "INTEGRATION_DELETE"
    case interactionCreate = "INTERACTION_CREATE"
    case inviteCreate = "INVITE_CREATE"
    case inviteDelete = "INVITE_DELETE"
    case messageCreate = "MESSAGE_CREATE"
    case messageUpdate = "MESSAGE_UPDATE"
    case messageDelete = "MESSAGE_DELETE"
    case messageDeleteBulk = "MESSAGE_DELETE_BULK"
    case messageReactionAdd = "MESSAGE_REACTION_ADD"
    case messageReactionRemove = "MESSAGE_REACTION_REMOVE"
    case messageReactionRemoveAll = "MESSAGE_REACTION_REMOVE_ALL"
    case messageReactionRemoveEmoji = "MESSAGE_REACTION_REMOVE_EMOJI"
    case presenceUpdate = "PRESENCE_UPDATE"
    case stageInstanceCreate = "STAGE_INSTANCE_CREATE"
    case stageInstanceDelete = "STAGE_INSTANCE_DELETE"
    case stageInstanceUpdate = "STAGE_INSTANCE_UPDATE"
    case typingStart = "TYPING_START"
    case userUpdate = "USER_UPDATE"
    case voiceStateUpdate = "VOICE_STATE_UPDATE"
    case voiceServerUpdate = "VOICE_SERVER_UPDATE"
    case webhooksUpdate = "WEBHOOKS_UPDATE"
    case applicationCommandPermissionsUpdate = "APPLICATION_COMMAND_PERMISSIONS_UPDATE"
    case autoModerationRuleCreate = "AUTO_MODERATION_RULE_CREATE"
    case autoModerationRuleUpdate = "AUTO_MODERATION_RULE_UPDATE"
    case autoModerationRuleDelete = "AUTO_MODERATION_RULE_DELETE"
    case autoModerationActionExecution = "AUTO_MODERATION_ACTION_EXECUTION"
}
