//
//  File.swift
//  
//
//  Created by Jia Chen Yee on 27/3/23.
//

import Foundation

public struct GatewayMessage: GatewayEventData {
    /// id of the message
    public var id: Snowflake
    
    /// id of the channel the message was sent in
    public var channelId: Snowflake
    
    /// the author of this message (not guaranteed to be a valid user, see below)
    public var author: User?
    
    /// contents of the message
    public var content: String
    
    /// when this message was sent
    public var timestamp: ISO8601Timestamp
    
    /// when this message was edited (or null if never)
    public var editedTimestamp: ISO8601Timestamp?
    
    /// whether this was a TTS message
    public var tts: Bool
    
    /// whether this message mentions everyone
    public var mentionEveryone: Bool
    
    /// users specifically mentioned in the message
    public var mentions: [User]
    
    /// roles specifically mentioned in this message
    public var mentionRoles: [Snowflake]
    
    /// channels specifically mentioned in this message
    public var mentionChannels: [ChannelMention]?
    
    /// any attached files
    public var attachments: [Attachment]
    
    /// any embedded content
    public var embeds: [Embed]
    
    /// reactions to the message
    public var reactions: [Reaction]?
    
    /// used for validating a message was sent
    public var nonce: Nonce?
    
    /// whether this message is pinned
    public var pinned: Bool
    
    /// if the message is generated by a webhook, this is the webhook's id
    public var webhookId: Snowflake?
    
    /// type of message
    public var type: MessageType
    
    /// sent with Rich Presence-related chat embeds
    public var activity: MessageActivity?
    
    /// sent with Rich Presence-related chat embeds
    public var application: Application?
    
    /// if the message is an Interaction or application-owned webhook, this is the id of the application
    public var applicationId: Snowflake?
    
    /// data showing the source of a crosspost, channel follow add, pin, or reply message
    public var messageReference: MessageReference?
    
    /// message flags combined as a bitfield
    public var flags: MessageFlags?
    
    /// the message associated with the message_reference
    public var referencedMessage: ReferencedMessage?
    
    /// sent if the message is a response to an Interaction
    public var interaction: Interaction?
    
    /// the thread that was started from this message, includes thread member object
    public var thread: Channel?
    
    /// sent if the message contains components like buttons, action rows, or other interactive components
    public var components: [Component]?
    
    /// sent if the message contains stickers
    public var stickerItems: [StickerItem]?
    
    /// Deprecated the stickers sent with the message
    public var stickers: [Sticker]?
    
    /// A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread, it can be used to estimate the relative position of the message in a thread in company with total_message_sent on parent thread
    public var position: Int?
    
    /// data of the role subscription purchase or renewal that prompted this ROLE_SUBSCRIPTION_PURCHASE message
    public var roleSubscriptionData: RoleSubscriptionData?
    
    /// ID of the guild the message was sent in - unless it is an ephemeral message
    public var guildId: Snowflake?
    
    /// Member properties for this message's author. Missing for ephemeral messages and messages from webhooks
    public var member: GuildMember?
    
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case channelId = "channel_id"
        case author = "author"
        case content = "content"
        case timestamp = "timestamp"
        case editedTimestamp = "edited_timestamp"
        case tts = "tts"
        case mentionEveryone = "mention_everyone"
        case mentions = "mentions"
        case mentionRoles = "mention_roles"
        case mentionChannels = "mention_channels"
        case attachments = "attachments"
        case embeds = "embeds"
        case reactions = "reactions"
        case nonce = "nonce"
        case pinned = "pinned"
        case webhookId = "webhook_id"
        case type = "type"
        case activity = "activity"
        case application = "application"
        case applicationId = "application_id"
        case messageReference = "message_reference"
        case flags = "flags"
        case referencedMessage = "referenced_message"
        case interaction = "interaction"
        case thread = "thread"
        case components = "components"
        case stickerItems = "sticker_items"
        case stickers = "stickers"
        case position = "position"
        case roleSubscriptionData = "role_subscription_data"
        case guildId = "guild_id"
        case member = "member"
    }
}
